# -*- coding: utf-8 -*-
"""Dashboard_AureaLitera.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g0xE2M38M0EgwSTYzi7vY_3CdUdn-Id8
"""

# ── CÉLULA 1: Instalação e imports ───────────────────────────────────────────
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import warnings
warnings.filterwarnings('ignore')

# Estilo global dos gráficos matplotlib
plt.rcParams.update({
    'figure.facecolor': '#0f0f1a',
    'axes.facecolor': '#1a1a2e',
    'axes.edgecolor': '#2e2e4e',
    'axes.labelcolor': '#e0e0ff',
    'xtick.color': '#a0a0cc',
    'ytick.color': '#a0a0cc',
    'text.color': '#e0e0ff',
    'grid.color': '#2e2e4e',
    'grid.linestyle': '--',
    'grid.alpha': 0.5,
    'font.family': 'monospace',
})

BG_DARK = '#0f0f1a'
BG_PANEL = '#1a1a2e'
ACCENT = '#7b68ee'
DESTAQUE = '#00d4aa'
print(" Bibliotecas carregadas com sucesso!")

# ── CÉLULA 2: Carregamento dos dados ─────────────────────────────────────────
CAMINHO_JSON = '/content/dashboardData.json'

with open(CAMINHO_JSON, 'r', encoding='utf-8') as f:
    base = json.load(f)

# Lendo os blocos do JSON para DataFrames pandas
df_formatos = pd.DataFrame(base['vendas_por_formato'])
df_mensal = pd.DataFrame(base['faturamento_mensal_2026'])
# Ordenando os livros pelos mais vendidos primeiro
df_livros = pd.DataFrame(base['top_5_livros_vendidos']).sort_values('vendas', ascending=True)

print(f" Arquivo gerado em: {base['gerado_em']}")
print(" Bases carregadas e estruturadas em tabelas locais!\n")
print(df_formatos)
print("-"*30)
print(df_mensal)

# ── CÉLULA 3: Visão Geral — KPIs ─────────────────────────────────────────────
kpis = base['kpis_gerais']

print("\n" + "="*50)
print(" DASHBOARD DE VENDAS (LIVRARIA) — KPIs GERAIS")
print("="*50)
print(f" 📊 Receita Total      : R$ {kpis['receita_total']:,.2f}")
print(f" 👥 Usuários Ativos    : {kpis['usuarios_ativos']:,}")
print(f" 🛒 Total de Pedidos   : {kpis['total_pedidos']:,}")
print(f" 📚 Livros Cadastrados : {kpis['livros_cadastrados']:,}")
print("="*50)

# ── CÉLULA 4: Gráfico — Vendas por Formato (E-book x Físico x Audiobook) ────
fig, axes = plt.subplots(1, 2, figsize=(16, 5))
fig.patch.set_facecolor(BG_DARK)
fig.suptitle(' ANÁLISE POR FORMATO', fontsize=16, fontweight='bold', color='#e0e0ff', y=1.02)

# Barra: Receita Total
ax1 = axes[0]
bars = ax1.bar(df_formatos['formato'], df_formatos['receita']/1000, color=df_formatos['cor'])
ax1.bar_label(bars, fmt='R$ %.1fk', padding=4, color='#e0e0ff', fontsize=10)
ax1.set_title('Receita por Formato (R$ Mil)', color='#e0e0ff')
ax1.set_ylabel('R$ (Mil)')
ax1.grid(axis='y')

# Donut: Quantidade de itens
ax2 = axes[1]
wedges, texts, autotexts = ax2.pie(
    df_formatos['quantidade'], labels=df_formatos['formato'],
    colors=df_formatos['cor'], autopct='%1.1f%%',
    startangle=140, wedgeprops=dict(width=0.4, edgecolor=BG_DARK, linewidth=3)
)
for text in texts + autotexts:
    text.set_color('#e0e0ff'); text.set_fontweight('bold')
for t in autotexts:
    t.set_color(BG_DARK)
ax2.set_title('Quantidade Vendida (%)', color='#e0e0ff')

plt.tight_layout()
plt.savefig('vendas_formato.png', dpi=150, facecolor=BG_DARK)
plt.show()

# ── CÉLULA 5: Gráfico — Evolução Mensal (Físico x Digital) ──────────────────
fig, ax = plt.subplots(figsize=(14, 6))
fig.patch.set_facecolor(BG_DARK)

x = np.arange(len(df_mensal['mes']))
width = 0.4

bar1 = ax.bar(x - width/2, df_mensal['fisico']/1000, width, label='Físico', color='#FF9800')
bar2 = ax.bar(x + width/2, df_mensal['digital']/1000, width, label='Digital', color='#4CAF50')

ax.bar_label(bar1, fmt='%.1fk', padding=3, color='#e0e0ff', fontsize=9)
ax.bar_label(bar2, fmt='%.1fk', padding=3, color='#e0e0ff', fontsize=9)

ax.set_title(' EVOLUÇÃO DE FATURAMENTO MENSAL 2026: Físico vs Digital', fontweight='bold', color='#e0e0ff', pad=20)
ax.set_xticks(x)
ax.set_xticklabels(df_mensal['mes'])
ax.set_ylabel('Receita (R$ Mil)')
ax.legend(facecolor=BG_PANEL, edgecolor='#2e2e4e', labelcolor='#e0e0ff')
ax.grid(axis='y')

plt.tight_layout()
plt.savefig('vendas_mensais.png', dpi=150, facecolor=BG_DARK)
plt.show()

# ── CÉLULA 6: Gráfico — Top 5 Livros ─────────────────────────────────────────
fig, ax = plt.subplots(figsize=(14, 6))
fig.patch.set_facecolor(BG_DARK)

bars = ax.barh(df_livros['titulo'] + "\n(" + df_livros['autor'] + ")", df_livros['vendas'], color=ACCENT, height=0.6)
ax.bar_label(bars, fmt='%d un.', padding=5, color=DESTAQUE, fontsize=10, fontweight='bold')

ax.set_title(' TOP 5 LIVROS MAIS VENDIDOS', fontweight='bold', color='#e0e0ff', pad=15)
ax.set_xlabel('Unidades Vendidas')
ax.grid(axis='x')

plt.tight_layout()
plt.savefig('vendas_livros.png', dpi=150, facecolor=BG_DARK)
plt.show()

# ── CÉLULA 7: Dashboard Interativo (Plotly) ──────────────────────────────────
# Criando layout 2x2 para acomodar a nova realidade
fig = make_subplots(
    rows=2, cols=2,
    specs=[[{"type": "bar"}, {"type": "pie"}],
           [{"type": "bar", "colspan": 2}, None]], # Gráfico de livros ocupará as duas colunas
    subplot_titles=[
        'Faturamento Mensal: Físico x Digital (R$)',
        'Participação de Receita por Formato',
        'Top 5 Livros Vendidos (Unidades)'
    ]
)

# 1. Gráfico Mensal - Stacked Bar (Fisico vs Digital)
fig.add_trace(go.Bar(
    x=df_mensal['mes'], y=df_mensal['digital'], name='Digital', marker_color='#4CAF50'
), row=1, col=1)

fig.add_trace(go.Bar(
    x=df_mensal['mes'], y=df_mensal['fisico'], name='Físico', marker_color='#FF9800'
), row=1, col=1)

fig.update_layout(barmode='stack') # Empilhar as colunas

# 2. Pizza Formato de Receita
fig.add_trace(go.Pie(
    labels=df_formatos['formato'], values=df_formatos['receita'],
    marker_colors=df_formatos['cor'], hole=0.4
), row=1, col=2)

# 3. Top 5 Livros Barras (Ordenação decrescente para Plotly visual)
df_livros_pl = df_livros.sort_values('vendas', ascending=True)
fig.add_trace(go.Bar(
    x=df_livros_pl['vendas'], y=df_livros_pl['titulo'], orientation='h',
    marker_color=ACCENT, name='Vendas',
    text=df_livros_pl['vendas'].astype(str) + " un.", textposition='outside'
), row=2, col=1)

# Aplicar Temas escuros do Plotly
fig.update_layout(
    title_text=' DASHBOARD INTERATIVO LIVRARIA 2026',
    title_font=dict(size=20, color='#e0e0ff'),
    plot_bgcolor='#1a1a2e',
    paper_bgcolor='#0f0f1a',
    font=dict(color='#e0e0ff', family='monospace'),
    height=800,
    legend=dict(bgcolor='#1a1a2e', bordercolor='#2e2e4e', borderwidth=1),
    showlegend=True
)

fig.update_xaxes(gridcolor='#2e2e4e', showgrid=True)
fig.update_yaxes(gridcolor='#2e2e4e', showgrid=True)

fig.write_html('dashboard_livraria.html')
fig.show()

print("\n Arquivos de Imagens e Dashboard interativo HTML ('dashboard_livraria.html') gerados com sucesso!")